### PR TITLE
HELP WITH THE MENU

### PR DESCRIPTION
**Pull request by ghost**
Please help, it is a lot harder than it seems.

Please note I have created three test files just so I have the correct interface.
Ignore the following files that has Trial in front of it. It will be deleted at the end.

### CODE REVIEW

**Review by jjanicefong — COMMENTED** [review]
Try using the TouchableOpacity instead of Highlight and wrap that with the Image tag.

**Comment by josephbondoc** [comment]
Sorry! I'm not too sure of a fix, but I do remember from the previous labs where we can set our module as a variable with the value of "null".  I might be wrong as I feel like you already did it

var blahblah = "null";



I know render() is a react documentation, but I haven't gotten the change to use it react native. Maybe try removing it and using return() for your UI state?

**Comment by sshenis** [comment]
> Sorry! I'm not too sure of a fix, but I do remember from the previous labs where we can set our module as a variable with the value of "null". I might be wrong as I feel like you already did it
> 
> var blahblah = "null";
> 
> image
> 
> I know render() is a react documentation, but I haven't gotten the change to use it react native. Maybe try removing it and using return() for your UI state?

Hey J, I was able to make it work with render (). Please check my code.

**Review by jjanicefong — APPROVED** [review]
I see that you managed to implement the Touch Opacity.

**Comment by josephbondoc** [comment]
Nice! You managed to implement Touch Opacity. Looks like its all good!

**Review by josephbondoc — APPROVED** [review]
Nice! You managed to implement Touch Opacity. Looks like its all good!

**Pull request merged**
