### PR TITLE
Help! Don't know how to wrap my variable!?!?!

### PR DESCRIPTION
**Pull request by josephbondoc**
Hi! Having trouble with my ScrollView button. Can't figure out a proper function in order to wrap my text with ScrollView

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Joseph, before going about the variable. Have you tried to see if you can make the body scrollable? Or are you working on it as static for now? How about try making it scrollable to see if the workload will be easier afterwards.

**Comment by josephbondoc** [comment]
Got it, with your advice I hardcoded the scroll view and now the text is scrollable from the start.

Now I'm having trouble making it not scrollable through a button. My current button right now does nothing @sshenis

**Review by jjanicefong — COMMENTED** [review]
Joseph, it's good you have both toggle buttons now and the Scroll View implemented. In regards to toggling the Scroll on and off have you tried using the same concept for the Modes? Try to use true and false statements. Also, make sure to add Text to your Scroll button under your Switch tag. In your Story styles, style your switch buttons / flex-direction.

**Review by Cynthiafeng — COMMENTED** [review]
updated*

**Comment by josephbondoc** [comment]
I have fixed my problem! I instead opted for a fix combining && within my state variables.

**Review by ghost — APPROVED** [review]
Your if and else statement is smart. It's good you added that. Based on the code it looks straightforward and simpler. It was more complicated when you first started on it.

**Review by jjanicefong — APPROVED** [review]
Looks like everything works properly. Just missing the inline toggle styling. Approved.

**Pull request merged**
