### PR TITLE
!HELP <Footer /> Story Name Picker 

### PR DESCRIPTION
**Pull request by jjanicefong**
I've got the basics down with the picker but I need help changing the text state.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Janice, for each picker item you added a value in. How exactly are you passing that value when you change options? Please find a way to output the new selected value so the interface will change.

**Review by ghost — COMMENTED** [review]
I'm not sure about this one but for line 11 and 14 in your Footer.js, it seems that it's hardcoded to be {newText}. Why don't you try passing "value" as it's value so it's dependant on when you change the options. If that makes sense. I'm not 100% sure.

**Comment by josephbondoc** [comment]
I've checked your last commit, and seems like the problem was fixed!!!!!

**Review by ghost — APPROVED** [review]
Good that the code is simplified. Thank you for updating the styles.

**Review by josephbondoc — APPROVED** [review]
Looks good! Conflicts are fixed.

**Pull request merged**
